### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by iProgramMC** [blackgamma7/Aidyn#1]
I'd suggest the following:
- Since you're using C++, it should be possible to use its features, for example the function `SetTerrain` should be `World::SetTerrain` as seen in the code
- Rename `manualCrash` to `assert` or something, it behaves similarly to an assert

**Comment by blackgamma7** [comment]
Thanks for the suggestions and apologizes for the long response, I'll get to work updating the existing code with namespaces and renaming manualCrash to assert.
